name: "Execute Delta Checks"
on:
    pull_request:
       types: [opened, edited]

jobs:
    run-central-governance:
        # Aponta diretamente para o arquivo central usando o padrão: Organizacao/RepoCentral/Caminho@Branch
        uses: ${{ github.repository_owner }}/.github/.github/workflows/main.yml@main
        permissions:
            pull-requests: write
            repository-projects: read
            contents: read